# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 749df650e5f532d5a57680f42495f02ee1d482d1a86f2264643423a92275a057c85c7dcc932accd838e80448bd16eb02b55fa5cdff6a48f46cf2ca31a05b846d

test:
  secret_key_base: 0181c83b9536445aa27b4ef60241215b2c002472b8e0bf00b249c61fd8b1ce9e5c307b0b18d7313f1b2a7321aba5ab66bce824d3f6887f5a3e04b98d78eaed1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
